---
driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

platforms:
  - name: centos-7
  - name: ubuntu-16.04
  - name: debian-9

provisioner:
  name: salt_solo
  formula: apache
  require_chef: false
  data_path: test
  pillars:
    top.sls:
      base:
        '*':
          - apache
    apache.sls:
      apache:
        manage_service_states: False
        VirtualHost:
          example.com:
            item: '*:8080'
            directives:
              - ServerAdmin: 'webmaster@example.com'
              - LogLevel: 'warn'
            containers:
              Location:
                -
                  item: '/test.html'
                  directives:
                    - Require: 'all granted'

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
            - apache
            - apache.config-ng
            - apache.vhosts.vhost-ng
            - apache.modules-ng
    verifier:
      name: shell
      remote_exec: true
      patterns:
        - test/shell/test.sh
      command: |
        pwd
        chmod +x /tmp/kitchen/data/shell/test.sh
        ls -l /tmp/kitchen/data/shell/test.sh
        bash /tmp/kitchen/data/shell/test.sh
  - name: apache_norestart
    provisioner:
      state_top:
        base:
          '*':
            - apache
      pillars:
        apache.sls:
          apache:
            manage_service_states: False
