sudo: required
language: python
services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: default-centos-7
    - INSTANCE: default-ubuntu-1604
    - INSTANCE: default-debian-9

script:
  - bundle exec kitchen verify ${INSTANCE}
  - sudo cat /etc/apache2/apache2.conf
